# Quarkus properties
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/presantis
quarkus.datasource.username=presantis
quarkus.datasource.password=presantis

# Hibernate
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Flyway
quarkus.flyway.migrate-at-start=true

# Security JWT
smallrye.jwt.verify.issuer=https://presantis.com/
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.verify.key.location=publicKey.pem

# OpenAPI
quarkus.swagger-ui.always-include=true

# Password hashing
# We will use jBcrypt manually in the AuthService
